BEGIN TRANSACTION;
CREATE TABLE `users` (
	`id`	INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE,
	`username`	TEXT,
	`password`	TEXT
);
CREATE TABLE "pantry" (
	`id`	INTEGER PRIMARY KEY AUTOINCREMENT,
	`name`	TEXT,
	`db_link`	TEXT,
	`weight`	REAL
);
;
COMMIT;
